/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wang_java_Learning_jni_JniDemo */

#ifndef _Included_com_wang_java_Learning_jni_JniDemo
#define _Included_com_wang_java_Learning_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wang_java_Learning_jni_JniDemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wang_java_1Learning_jni_JniDemo_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
