#Ecommerce Monitor Configuration
#Sat Aug 16 17:06:23 CST 2025
website.jd.url=https://search.jd.com/Search?keyword=%E7%9B%B8%E6%9C%BA&enc=utf-8&wq=%E7%9B%B8%E6%9C%BA&pvid=fc7c226a49a24d449b61b47c9d4cbe79
check.interval.minutes=30
website.jd.id.attr=data-sku
website.jd.selector=.product-item

